#!/bin/bash

set -e

sudo systemctl restart isuumo.go.service
sleep 5
echo | sudo tee /var/log/nginx/access.log

echo "bench start"
sudo /home/isucon/isuumo/bench/bench -target-url http://127.0.0.1

sudo cat /var/log/nginx/access.log | alp ltsv -m "/api/chair/[0-9]+,/api/chair/buy/[0-9]+,/api/estate/[0-9]+,/api/estate/req_doc/[0-9]+,/api/recommended_estate/[0-9]+" --sort avg -r
